### PR TITLE
Update to new osl-firewall cookbook

### PR DESCRIPTION
**Pull request by detjensrobert**
Some other cleanup:
- `attributes` was empty, so I removed it.
- Merged duplicate logic in the Inspec tests
- Removed C6 support as `osl-firewall` does not support C6

### CODE REVIEW

**Comment by detjensrobert** [comment]
[osl-nfs](https://trello.com/c/gKLwPr19/2117-osl-nfs)

**Comment by ramereth** [comment]
LGTM

**Review by ramereth — APPROVED** [review]

**Comment by detjensrobert** [comment]
!bump major

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a major-level version bump to v2.0.0.  Have a nice day!

**Pull request merged**
