### PR TITLE
Update to Chef 17

### PR DESCRIPTION
**Pull request by EMH333**
Note: `nfs v4.0.0` only works on CentOS 7

### CODE REVIEW

**Comment by ramereth** [comment]
@EMH333 can you please test this against this PR? https://github.com/sous-chefs/yum-centos/pull/53

**Comment by EMH333** [comment]
> @EMH333 can you please test this against this PR? [sous-chefs/nfs#121](https://github.com/sous-chefs/nfs/pull/121)

All tests pass on all platforms!

**Comment by ramereth** [comment]
@EMH333 can you please re-enable the idempotency tests

**Comment by EMH333** [comment]
Yep! Everything passes :tada:

**Review by ramereth — APPROVED** [review]
Minor bump.

Once merged and deploy, can you please go through all of our cookbooks that depend on this that may have `enforce_idempotency: false` due to this before? I believe this includes at least osl-haproxy and osl-nodes (maybe others).

**Comment by EMH333** [comment]
!bump minor ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v2.1.0.  Have a nice day!

**Pull request merged**
